pipeline {
    agent {
        docker {
            image 'python:3.13'
        }
    }

    stages {
        stage('Lint Code') {
            steps {
                sh 'pip install flake8'
                sh 'flake8 . --exclude=migrations,venv --max-line-length=120'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pip install -r requirements.txt'
                sh 'python manage.py test'
            }
        }

        stage('Build Docker Images') {
            steps {
                sh 'docker-compose build'
            }
        }
    }

    post {
        always {
            echo 'Pipeline completed.'
        }
        failure {
            echo 'Build failed!'
        }
    }
}
